/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package damkar;

import java.util.UUID;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class FormProses extends javax.swing.JFrame {

    private String id_laporan;
    private DefaultListModel<String> listModel;

    public FormProses() {
        initComponents();
        this.id_laporan = id_laporan;

        listModel = new DefaultListModel<String>();
        li_regu.setModel(listModel);

        pangkat_regu();
        isi_cbbUnit();

    }

    private void pangkat_regu() {
        cbPangkat.removeAllItems();

        cbPangkat.addItem("Komandan Regu");
        cbPangkat.addItem("Operator");
        cbPangkat.addItem("Anggota PNS");
        cbPangkat.addItem("Anggota Non-PNS");
        cbPangkat.addItem("Driver");
    }

    private void isi_cbbUnit() {
        String sql = "SELECT id_unit,jenis_unit from unit_damkar where status = 'Tersedia'";

        try {
            Connection conn = damkar.Koneksi.db_koneksi();
            PreparedStatement pst = conn.prepareCall(sql);
            ResultSet rs = pst.executeQuery();

            cbUnit.removeAllItems();

            while (rs.next()) {
                String id = rs.getString("id_unit");
                String jenis = rs.getString("jenis_unit");
                cbUnit.addItem(id + " - " + jenis);
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Gagal memuat data unit: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbUnit = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfPetugas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPangkat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnKirimRegu = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        li_regu = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PROSES LAPORAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UNIT");

        cbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUnitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PETUGAS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PANGKAT");

        cbPangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REGU YANG DIKIRIM");

        btnKirimRegu.setBackground(new java.awt.Color(255, 255, 0));
        btnKirimRegu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKirimRegu.setText("KIRIM REGU");
        btnKirimRegu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimReguActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 255, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        li_regu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(li_regu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPetugas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(cbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah)
                            .addComponent(cbPangkat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnKirimRegu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbPangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKirimRegu)
                    .addComponent(btnTambah))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKirimReguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimReguActionPerformed
        // TODO add your handling code here:
        if (cbUnit.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Pilih unit terlebih dahulu MasPur!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (listModel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tambahkan minimal satu petugas ke dalam regu MasPur!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Anda yakin ingin mengirim regu ini? ",
                "PERINGATAN", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            Connection conn = damkar.Koneksi.db_koneksi();

            String unit_terpilih = cbUnit.getSelectedItem().toString();
            String id_unit = unit_terpilih.split(" - ")[0];

            for (int i = 0; i < listModel.getSize(); i++) {

                String data_regu = listModel.getElementAt(i);

                String[] parts = data_regu.split(" - ");
                String nama_petugas = parts[0].trim();
                String pangkat = parts[1].trim();

                String id_petugas = "PTG-" + UUID.randomUUID().toString().substring(0, 4).toUpperCase();
                String sql_petugas
                        = "INSERT INTO petugas "
                        + "(id_petugas,nama_petugas,pangkat) "
                        + "VALUES (?,?,?)";

                PreparedStatement pst_petugas = conn.prepareStatement(sql_petugas);
                pst_petugas.setString(1, id_petugas);
                pst_petugas.setString(2, nama_petugas);
                pst_petugas.setString(3, pangkat);
                pst_petugas.executeUpdate();
                pst_petugas.close();
                String sql_penugasan
                        = "INSERT INTO penugasan"
                        + "(id_penugasan,id_laporan,id_petugas,id_unit) "
                        + "VALUES (?,?,?,?)";

                PreparedStatement pst_penugasan = conn.prepareStatement(sql_penugasan);
                String id_penugasan = "TGS-" + UUID.randomUUID().toString().substring(0, 4).toUpperCase();
                pst_penugasan.setString(1, id_penugasan);
                pst_penugasan.setString(2, this.id_laporan);
                pst_penugasan.setString(3, id_petugas);
                pst_penugasan.setString(4, id_unit);
                pst_penugasan.executeUpdate();

                String sql_updateLaporan
                        = "UPDATE laporan "
                        + "SET status_laporan = 'diproses' "
                        + "where id_laporan = ?;";

                PreparedStatement pst_updateLaporan = conn.prepareStatement(sql_updateLaporan);
                pst_updateLaporan.setString(1, this.id_laporan);
                pst_updateLaporan.executeUpdate();

                String sql_updateUnit
                        = "UPDATE unit_damkar "
                        + "SET status = 'Bertugas' "
                        + "where id_unit = ?";
                PreparedStatement pst_updateUnit = conn.prepareCall(sql_updateUnit);
                pst_updateUnit.setString(1, id_unit);
                pst_updateUnit.executeUpdate();

                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        MenuLaporan ml = new MenuLaporan();
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setResizable(false);
        ml.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnKirimReguActionPerformed

    private void cbUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUnitActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nama_petugas = tfPetugas.getText();

        if (nama_petugas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama petugas tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String pangkat = cbPangkat.getSelectedItem().toString();

        String data_regu = nama_petugas + " - " + pangkat;

        listModel.addElement(data_regu);

        tfPetugas.setText("");
        tfPetugas.requestFocus();
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKirimRegu;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbPangkat;
    private javax.swing.JComboBox<String> cbUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> li_regu;
    private javax.swing.JTextField tfPetugas;
    // End of variables declaration//GEN-END:variables
}
