/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package damkar;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuLaporan extends javax.swing.JFrame {

    DefaultTableModel model;

    public MenuLaporan() {
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("ID-Laporan");
        model.addColumn("pelapor");
        model.addColumn("alamat");
        model.addColumn("waktu");
        model.addColumn("jenis");
        model.addColumn("kontak");
        model.addColumn("status");
        model.addColumn("Regu");

        jTable1.setModel(model);

        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);

        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void tampil_data() {

        try {
            Connection conn = damkar.Koneksi.db_koneksi();
            String sql = "SELECT l.id_laporan, l.pelapor, l.alamat,l.waktu_laporan,l.jenis_laporan,"
                    + "l.kontak_pelapor,l.status_laporan,u.nama_unit "
                    + "FROM laporan l "
                    + "LEFT JOIN penugasan pg ON l.id_laporan = pg.id_laporan "
                    + "LEFT JOIN unit_damkar u ON pg.id_unit = u.id_unit "
                    + "WHERE l.status_laporan != 'Selesai' "
                    + "GROUP BY l.id_laporan "
                    + "ORDER BY l.waktu_laporan DESC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String id_laporan = rs.getString("id_laporan");
                String pelapor = rs.getString("pelapor");
                String alamat = rs.getString("alamat");
                String waktu = rs.getString("waktu_laporan");
                String jenis = rs.getString("jenis_laporan");
                String kontak = rs.getString("kontak_pelapor");
                String status = rs.getString("status_laporan");
                String unit = rs.getString("nama_unit");

                if (unit == null) {
                    unit = "-";
                }

                model.addRow(new Object[]{
                    id_laporan, pelapor, alamat, waktu, jenis, kontak, status, unit
                });

            }

            pst.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPelapor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAalamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tfWaktu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfKontak = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbBaru = new javax.swing.JRadioButton();
        rbDiproses = new javax.swing.JRadioButton();
        rbSelesai = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        tfJenisLaporan = new javax.swing.JTextField();
        btnPelapor = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        btnDasboard = new javax.swing.JButton();
        btnProsesLaporan = new javax.swing.JButton();
        btnArmada = new javax.swing.JButton();
        btnDetailRegu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU LAPORAN KEBAKARAN");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-firefighter-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel7)
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PELAPOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ALAMAT");

        tfPelapor.setEditable(false);
        tfPelapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPelaporActionPerformed(evt);
            }
        });

        TAalamat.setEditable(false);
        TAalamat.setColumns(20);
        TAalamat.setRows(5);
        jScrollPane1.setViewportView(TAalamat);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WAKTU");

        tfWaktu.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KONTAK");

        tfKontak.setEditable(false);
        tfKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKontakActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STATUS LAPORAN");

        rbBaru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbBaru.setForeground(new java.awt.Color(255, 255, 255));
        rbBaru.setText("BARU");
        rbBaru.setEnabled(false);

        rbDiproses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbDiproses.setForeground(new java.awt.Color(204, 0, 0));
        rbDiproses.setText("DIPROSES");
        rbDiproses.setEnabled(false);

        rbSelesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbSelesai.setForeground(new java.awt.Color(0, 255, 51));
        rbSelesai.setText("SELESAI");
        rbSelesai.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JENIS");

        tfJenisLaporan.setEditable(false);

        btnPelapor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPelapor.setText("FROM PELAPOR");
        btnPelapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelaporActionPerformed(evt);
            }
        });

        btnSelesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnDasboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDasboard.setText("DASHBOARD");
        btnDasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDasboardActionPerformed(evt);
            }
        });

        btnProsesLaporan.setBackground(new java.awt.Color(51, 153, 255));
        btnProsesLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProsesLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnProsesLaporan.setText("PROSES LAPORAN");
        btnProsesLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesLaporanActionPerformed(evt);
            }
        });

        btnArmada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnArmada.setText("ARMADA");
        btnArmada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArmadaActionPerformed(evt);
            }
        });

        btnDetailRegu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetailRegu.setText("LIHAT DETAIL REGU");
        btnDetailRegu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailReguActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TABEL LAPORAN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(tfPelapor)
                    .addComponent(tfJenisLaporan))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfKontak))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfWaktu))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(btnProsesLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 236, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbBaru)
                                        .addGap(69, 69, 69)
                                        .addComponent(rbSelesai))
                                    .addComponent(rbDiproses))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnPelapor)
                .addGap(18, 18, 18)
                .addComponent(btnSelesai)
                .addGap(18, 18, 18)
                .addComponent(btnDasboard)
                .addGap(50, 50, 50)
                .addComponent(btnArmada)
                .addGap(18, 18, 18)
                .addComponent(btnDetailRegu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(371, 371, 371))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbBaru)
                                    .addComponent(rbSelesai))
                                .addGap(18, 18, 18)
                                .addComponent(rbDiproses))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfPelapor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProsesLaporan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPelapor)
                    .addComponent(btnSelesai)
                    .addComponent(btnDasboard)
                    .addComponent(btnArmada)
                    .addComponent(btnDetailRegu))
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPelaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPelaporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPelaporActionPerformed

    private void tfKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontakActionPerformed

    private void btnPelaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelaporActionPerformed
        // TODO add your handling code here:
        FormPelapor ml = new FormPelapor();
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setResizable(false);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPelaporActionPerformed

    private void btnDasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDasboardActionPerformed
        // TODO add your handling code here:
        Dasboard ml = new Dasboard();
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setResizable(false);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDasboardActionPerformed

    private void btnArmadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArmadaActionPerformed
        // TODO add your handling code here:
        MenuArmada ml = new MenuArmada();
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setResizable(false);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArmadaActionPerformed

    private void btnDetailReguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailReguActionPerformed
        // TODO add your handling code here:
        int baris_terpilih = jTable1.getSelectedRow();
        if (baris_terpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan diproses terlebih dahulu MasPur!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id_laporan = jTable1.getValueAt(baris_terpilih, 0).toString();

        DetailRegu ml = new DetailRegu(id_laporan);
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDetailReguActionPerformed

    private void btnProsesLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesLaporanActionPerformed
        // TODO add your handling code here:
        int baris_terpilih = jTable1.getSelectedRow();
        if (baris_terpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan diproses terlebih dahulu !", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String id_laporan = jTable1.getValueAt(baris_terpilih, 0).toString();

        String status = jTable1.getValueAt(baris_terpilih, 6).toString();
        if (!status.equals("baru")) {
            JOptionPane.showMessageDialog(this, "Laporan ini sudah selesai atau sedang ditangani!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        FormProses ml = new FormProses(id_laporan);
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setResizable(false);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProsesLaporanActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        int baris_terpilih = jTable1.getSelectedRow();

        String status_lama = jTable1.getValueAt(baris_terpilih, 6).toString();

        if (status_lama.equalsIgnoreCase("baru")) {
            JOptionPane.showMessageDialog(this, "Kirimkan Dulu regunya ", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (baris_terpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan diubah statusnya!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String status_terpilih = "Selesai";
        String id_laporan = jTable1.getValueAt(baris_terpilih, 0).toString();
        String id_unit = null;

        try {
            Connection conn = damkar.Koneksi.db_koneksi();
            String sql_cariID_unit = "SELECT id_unit FROM penugasan WHERE id_laporan = ? LIMIT 1";

            PreparedStatement pst_cariID_unit = conn.prepareCall(sql_cariID_unit);
            pst_cariID_unit.setString(1, id_laporan);
            ResultSet rs_cariID_unit = pst_cariID_unit.executeQuery();

            if (rs_cariID_unit.next()) {
                id_unit = rs_cariID_unit.getString("id_unit");
            }

            if (id_unit != null) {
                String sql_update_unit = "UPDATE unit_damkar SET status = 'Tersedia' WHERE id_unit = ?";
                PreparedStatement pst_updateUnit = conn.prepareStatement(sql_update_unit);
                pst_updateUnit.setString(1, id_unit);
                pst_updateUnit.executeUpdate();

            }
            String sql_updateLaporan = "UPDATE laporan SET status_laporan = ? WHERE id_laporan = ?";
            PreparedStatement pst_updateLaporan = conn.prepareStatement(sql_updateLaporan);
            pst_updateLaporan.setString(1, status_terpilih);
            pst_updateLaporan.setString(2, id_laporan);
            pst_updateLaporan.executeUpdate();

            JOptionPane.showMessageDialog(this, "Status laporan berhasil diperbarui !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error");
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {
            tfPelapor.setText(model.getValueAt(selectedRow, 1).toString());
            TAalamat.setText(model.getValueAt(selectedRow, 2).toString());
            tfWaktu.setText(model.getValueAt(selectedRow, 3).toString());
            tfJenisLaporan.setText(model.getValueAt(selectedRow, 4).toString());
            tfKontak.setText(model.getValueAt(selectedRow, 5).toString());

            String status = model.getValueAt(selectedRow, 6).toString();

            switch (status) {

                case "baru":
                    rbBaru.setSelected(true);
                    break;

                case "diproses":
                    rbDiproses.setSelected(true);
                    break;

                case "selesai":
                    rbSelesai.setSelected(true);
                    break;
            }

        }

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAalamat;
    private javax.swing.JButton btnArmada;
    private javax.swing.JButton btnDasboard;
    private javax.swing.JButton btnDetailRegu;
    private javax.swing.JButton btnPelapor;
    private javax.swing.JButton btnProsesLaporan;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbBaru;
    private javax.swing.JRadioButton rbDiproses;
    private javax.swing.JRadioButton rbSelesai;
    private javax.swing.JTextField tfJenisLaporan;
    private javax.swing.JTextField tfKontak;
    private javax.swing.JTextField tfPelapor;
    private javax.swing.JTextField tfWaktu;
    // End of variables declaration//GEN-END:variables
}
