package damkar02;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author yan
 */
public class Form_pelapor extends javax.swing.JFrame {

    /**
     * Creates new form Form_pelapor
     */
    public Form_pelapor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_pelapor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tf_jenis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_kontak = new javax.swing.JTextField();
        cb_kirim = new javax.swing.JButton();
        btn_menuLaporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/e911_avatar_30.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM PELAPOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PELAPOR");

        tf_pelapor.setBackground(new java.awt.Color(0, 0, 51));
        tf_pelapor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_pelapor.setForeground(new java.awt.Color(255, 255, 255));
        tf_pelapor.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_pelapor.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_pelapor.setPreferredSize(new java.awt.Dimension(71, 26));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ALAMAT");

        ta_alamat.setBackground(new java.awt.Color(0, 0, 51));
        ta_alamat.setColumns(20);
        ta_alamat.setForeground(new java.awt.Color(255, 255, 255));
        ta_alamat.setRows(5);
        ta_alamat.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ta_alamat);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JENIS");

        tf_jenis.setBackground(new java.awt.Color(0, 0, 51));
        tf_jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_jenis.setForeground(new java.awt.Color(255, 255, 255));
        tf_jenis.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_jenis.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_jenis.setPreferredSize(new java.awt.Dimension(71, 26));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KONTAK");

        tf_kontak.setBackground(new java.awt.Color(0, 0, 51));
        tf_kontak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_kontak.setForeground(new java.awt.Color(255, 255, 255));
        tf_kontak.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_kontak.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_kontak.setPreferredSize(new java.awt.Dimension(71, 26));

        cb_kirim.setBackground(new java.awt.Color(51, 0, 0));
        cb_kirim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cb_kirim.setForeground(new java.awt.Color(255, 255, 255));
        cb_kirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_upload_progress_25.png"))); // NOI18N
        cb_kirim.setText("KIRIM LAPORAN");
        cb_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kirimActionPerformed(evt);
            }
        });

        btn_menuLaporan.setBackground(new java.awt.Color(51, 0, 0));
        btn_menuLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_menuLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_menuLaporan.setText("MN LPR");
        btn_menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(tf_pelapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_menuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addGap(59, 59, 59))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_pelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kirimActionPerformed
        // TODO add your handling code here:
        String pelapor = tf_pelapor.getText();
        String alamat = ta_alamat.getText();
        String jenis = tf_jenis.getText();
        
        LocalDateTime sekarang = LocalDateTime.now();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String waktu = sekarang.format(format);
        
        String kontak = tf_kontak.getText();
        String status = "baru";
        
        if(pelapor.isEmpty() || alamat.isEmpty() || jenis.isEmpty() || kontak.isEmpty()){
            JOptionPane.showMessageDialog(null,"eemua field harus dihapus MasPur",
                    "PERINGATAN",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try{
            java.sql.Connection conn = damkar02.Koneksi.dB_koneksi();
            String sql = "INSERT INTO laporan "
                    + "(id_laporan,pelapor,alamat,waktu_laporan,kontak_pelapor,jenis_laporan,status_laporan) "
                    + "VALUES(?,?,?,?,?,?,?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            String id_laporan = "LRP-" + UUID.randomUUID().toString().substring(0,4);
            
            pst.setString(1, id_laporan);
            pst.setString(2,pelapor);
            pst.setString(3,alamat);
            pst.setString(4, waktu);
            pst.setString(5,kontak);
            pst.setString(6, jenis);
            pst.setString(7, status);
            
            pst.executeUpdate();
            pst.close();
            
            tf_pelapor.setText("");
            tf_pelapor.requestFocus();
            
            ta_alamat.setText("");
            ta_alamat.requestFocus();
            
            tf_jenis.setText("");
            tf_jenis.requestFocus();
            
            tf_kontak.setText("");
            tf_kontak.requestFocus();
            
            JOptionPane.showMessageDialog(this,"LAPORAN BERHASIL DIKIRIM MASPUR!");
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_kirimActionPerformed

    private void btn_menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuLaporanActionPerformed
        // TODO add your handling code here:
        Menu_laporan2 ml = new Menu_laporan2();
        ml.pack();
        ml.setLocationRelativeTo(null);
        ml.setResizable(false);
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuLaporanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_menuLaporan;
    private javax.swing.JButton cb_kirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JTextField tf_jenis;
    private javax.swing.JTextField tf_kontak;
    private javax.swing.JTextField tf_pelapor;
    // End of variables declaration//GEN-END:variables
}
