package damkar02;

import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class Menu_laporan2 extends javax.swing.JFrame {

    DefaultTableModel model;

    public Menu_laporan2() {
        initComponents();

        model = new DefaultTableModel();
        model.addColumn("ID-Laporan");
        model.addColumn("pelapor");
        model.addColumn("alamat");
        model.addColumn("waktu");
        model.addColumn("jenis");
        model.addColumn("kontak");
        model.addColumn("status");
        model.addColumn("Regu");

        jTable1.setModel(model);

        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);

        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_armada = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_jenis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        tf_pelapor = new javax.swing.JTextField();
        tf_waktu = new javax.swing.JTextField();
        tf_kontak = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rb_masuk = new javax.swing.JRadioButton();
        rb_diproses = new javax.swing.JRadioButton();
        rb_selesai = new javax.swing.JRadioButton();
        bt_proses = new javax.swing.JButton();
        btn_selesai = new javax.swing.JButton();
        btn_liatRegu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAPORAN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/assignment_add_50.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(51, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard_25dp.png"))); // NOI18N
        jButton1.setText("DASHBOARD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_armada.setBackground(new java.awt.Color(51, 0, 0));
        btn_armada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_armada.setForeground(new java.awt.Color(255, 255, 255));
        btn_armada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fire_truck_25.png"))); // NOI18N
        btn_armada.setText("ARMADA UNIT");
        btn_armada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_armadaActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/e911_avatar_25.png"))); // NOI18N
        jButton4.setText("FORM PELAPOR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_25.png"))); // NOI18N
        jButton3.setText("KELUAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_armada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_armada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORM LAPORAN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(535, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PELAPOR");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ALAMAT");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JENIS");

        tf_jenis.setEditable(false);
        tf_jenis.setBackground(new java.awt.Color(0, 0, 51));
        tf_jenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_jenis.setForeground(new java.awt.Color(255, 255, 255));
        tf_jenis.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_jenis.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_jenis.setPreferredSize(new java.awt.Dimension(71, 26));

        ta_alamat.setEditable(false);
        ta_alamat.setBackground(new java.awt.Color(0, 0, 51));
        ta_alamat.setColumns(20);
        ta_alamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ta_alamat.setForeground(new java.awt.Color(255, 255, 255));
        ta_alamat.setRows(5);
        ta_alamat.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ta_alamat);

        tf_pelapor.setEditable(false);
        tf_pelapor.setBackground(new java.awt.Color(0, 0, 51));
        tf_pelapor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_pelapor.setForeground(new java.awt.Color(255, 255, 255));
        tf_pelapor.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_pelapor.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_pelapor.setPreferredSize(new java.awt.Dimension(71, 26));

        tf_waktu.setEditable(false);
        tf_waktu.setBackground(new java.awt.Color(0, 0, 51));
        tf_waktu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_waktu.setForeground(new java.awt.Color(255, 255, 255));
        tf_waktu.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_waktu.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_waktu.setPreferredSize(new java.awt.Dimension(71, 26));

        tf_kontak.setEditable(false);
        tf_kontak.setBackground(new java.awt.Color(0, 0, 51));
        tf_kontak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_kontak.setForeground(new java.awt.Color(255, 255, 255));
        tf_kontak.setCaretColor(new java.awt.Color(255, 255, 255));
        tf_kontak.setMinimumSize(new java.awt.Dimension(64, 25));
        tf_kontak.setPreferredSize(new java.awt.Dimension(71, 26));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("STATUS");

        rb_masuk.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(rb_masuk);
        rb_masuk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_masuk.setForeground(new java.awt.Color(255, 255, 255));
        rb_masuk.setText("MASUK ");
        rb_masuk.setEnabled(false);

        rb_diproses.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(rb_diproses);
        rb_diproses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_diproses.setForeground(new java.awt.Color(255, 255, 255));
        rb_diproses.setText("DIPROSES");
        rb_diproses.setEnabled(false);
        rb_diproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_diprosesActionPerformed(evt);
            }
        });

        rb_selesai.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(rb_selesai);
        rb_selesai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_selesai.setForeground(new java.awt.Color(255, 255, 255));
        rb_selesai.setText("SELESAI");
        rb_selesai.setEnabled(false);

        bt_proses.setBackground(new java.awt.Color(51, 0, 0));
        bt_proses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_proses.setForeground(new java.awt.Color(255, 255, 255));
        bt_proses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_upload_progress_25.png"))); // NOI18N
        bt_proses.setText("PROSES LAPORAN");
        bt_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_prosesActionPerformed(evt);
            }
        });

        btn_selesai.setBackground(new java.awt.Color(51, 0, 0));
        btn_selesai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_selesai.setForeground(new java.awt.Color(255, 255, 255));
        btn_selesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/assignment_turned_in_25dp.png"))); // NOI18N
        btn_selesai.setText("SELESAI");
        btn_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selesaiActionPerformed(evt);
            }
        });

        btn_liatRegu.setBackground(new java.awt.Color(51, 0, 0));
        btn_liatRegu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_liatRegu.setForeground(new java.awt.Color(255, 255, 255));
        btn_liatRegu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/groups_25dp.png"))); // NOI18N
        btn_liatRegu.setText("LIAT REGU");
        btn_liatRegu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_liatReguActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TABLE LAPORAN");

        jTable1.setBackground(new java.awt.Color(0, 0, 51));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KONTAK");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("WAKTU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tf_pelapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(rb_masuk))
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_diproses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_selesai))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_proses, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_liatRegu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(tf_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_masuk)
                                    .addComponent(rb_diproses)
                                    .addComponent(rb_selesai)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(99, 99, 99)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(bt_proses)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_pelapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(tf_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_selesai)
                            .addComponent(btn_liatRegu))
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampil_data() {

        try {
            Connection conn = damkar02.Koneksi.dB_koneksi();
            String sql = "SELECT l.id_laporan, l.pelapor, l.alamat,l.waktu_laporan,l.jenis_laporan,"
                    + "l.kontak_pelapor,l.status_laporan,u.nama_unit "
                    + "FROM laporan l "
                    + "LEFT JOIN penugasan pg ON l.id_laporan = pg.id_laporan "
                    + "LEFT JOIN unit_damkar u ON pg.id_unit = u.id_unit "
                    + "WHERE l.status_laporan != 'Selesai' "
                    + "GROUP BY l.id_laporan "
                    + "ORDER BY l.waktu_laporan DESC";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String id_laporan = rs.getString("id_laporan");
                String pelapor = rs.getString("pelapor");
                String alamat = rs.getString("alamat");
                String waktu = rs.getString("waktu_laporan");
                String jenis = rs.getString("jenis_laporan");
                String kontak = rs.getString("kontak_pelapor");
                String status = rs.getString("status_laporan");
                String unit = rs.getString("nama_unit");

                if (unit == null) {
                    unit = "-";
                }

                model.addRow(new Object[]{
                    id_laporan, pelapor, alamat, waktu, jenis, kontak, status, unit
                });

            }

            pst.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dashboard p = new Dashboard();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_armadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_armadaActionPerformed
        // TODO add your handling code here:
        Menu_armada p = new Menu_armada();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
    }//GEN-LAST:event_btn_armadaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Form_pelapor p = new Form_pelapor();
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rb_diprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_diprosesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_diprosesActionPerformed

    private void bt_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_prosesActionPerformed
        // TODO add your handling code here:
        int baris_terpilih = jTable1.getSelectedRow();
        if (baris_terpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan diproses terlebih dahulu MasPur!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id_laporan = jTable1.getValueAt(baris_terpilih, 0).toString();
        
        String status = jTable1.getValueAt(baris_terpilih, 6).toString();
        if(!status.equals("baru")){
            JOptionPane.showMessageDialog(this, "Laporan ini sudah selesai atau sedang ditangani MasPur!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        Proses_laporan p = new Proses_laporan(id_laporan);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_prosesActionPerformed

    private void btn_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selesaiActionPerformed
        // TODO add your handling code here:
        int baris_terpilih = jTable1.getSelectedRow();
        
        String status_lama = jTable1.getValueAt(baris_terpilih, 6).toString();
        
        if(status_lama.equalsIgnoreCase("baru")){
            JOptionPane.showMessageDialog(this, "Kirimkan Dulu regunya MasPur", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(baris_terpilih == -1){
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan diubah statusnya!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String status_terpilih = "Selesai";
        String id_laporan = jTable1.getValueAt(baris_terpilih, 0).toString();
        String id_unit = null;
        
        try{
            Connection conn = damkar02.Koneksi.dB_koneksi();
            String sql_cariID_unit = "SELECT id_unit FROM penugasan WHERE id_laporan = ? LIMIT 1";
            
            PreparedStatement pst_cariID_unit = conn.prepareCall(sql_cariID_unit);
            pst_cariID_unit.setString(1,id_laporan);
            ResultSet rs_cariID_unit = pst_cariID_unit.executeQuery();
            
            if(rs_cariID_unit.next()){
                id_unit = rs_cariID_unit.getString("id_unit");
            }
            
            if(id_unit != null){
                String sql_update_unit = "UPDATE unit_damkar SET status = 'Tersedia' WHERE id_unit = ?";
                PreparedStatement pst_updateUnit = conn.prepareStatement(sql_update_unit);
                pst_updateUnit.setString(1, id_unit);
                pst_updateUnit.executeUpdate();
                
            }
            String sql_updateLaporan = "UPDATE laporan SET status_laporan = ? WHERE id_laporan = ?";
            PreparedStatement pst_updateLaporan = conn.prepareStatement(sql_updateLaporan);
            pst_updateLaporan.setString(1, status_terpilih);
            pst_updateLaporan.setString(2, id_laporan);
            pst_updateLaporan.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Status laporan berhasil diperbarui MasPur!");
            
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"error MasPur");
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btn_selesaiActionPerformed

    private void btn_liatReguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_liatReguActionPerformed
        // TODO add your handling code here:
        int baris_terpilih = jTable1.getSelectedRow();
        if (baris_terpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan diproses terlebih dahulu MasPur!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id_laporan = jTable1.getValueAt(baris_terpilih, 0).toString();
        
        
        Detail_regu p = new Detail_regu(id_laporan);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setVisible(true);

    }//GEN-LAST:event_btn_liatReguActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {
            tf_pelapor.setText(model.getValueAt(selectedRow, 1).toString());
            ta_alamat.setText(model.getValueAt(selectedRow, 2).toString());
            tf_waktu.setText(model.getValueAt(selectedRow, 3).toString());
            tf_jenis.setText(model.getValueAt(selectedRow, 4).toString());
            tf_kontak.setText(model.getValueAt(selectedRow, 5).toString());

            String status = model.getValueAt(selectedRow, 6).toString();

            switch (status) {

                case "baru":
                    rb_masuk.setSelected(true);
                    break;

                case "diproses":
                    rb_diproses.setSelected(true);
                    break;

                case "selesai":
                    rb_masuk.setSelected(true);
                    break;
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_proses;
    private javax.swing.JButton btn_armada;
    private javax.swing.JButton btn_liatRegu;
    private javax.swing.JButton btn_selesai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb_diproses;
    private javax.swing.JRadioButton rb_masuk;
    private javax.swing.JRadioButton rb_selesai;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JTextField tf_jenis;
    private javax.swing.JTextField tf_kontak;
    private javax.swing.JTextField tf_pelapor;
    private javax.swing.JTextField tf_waktu;
    // End of variables declaration//GEN-END:variables
}
